title: Flag&Safe
description: Digitale Soforthilfe bei problematischen Inhalten, Förderung der Selbstwirksamkeit von jungen Nutzer:innen, und institutionelle Vernetzung für eine sichere Online-Schweiz
theme: minima
baseurl: ""
url: ""

# Social media links
social_links:
  github: Flag-Safe

# Build settings
markdown: kramdown
permalink: /:title/